sudo: required
services: 
    - docker 

before_install:
    - docker build -t egovelox/docker-react -f Dockerfile.dev .


# script:
#    - docker run egovelox/docker-react npm run test -- --coverage

script:
    - docker run -e CI=true egovelox/docker-react npm run test

deploy: 
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-3-454187822577"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY