sudo: required
services: 
    - docker 

before_install:
    - docker build -t egovelox/docker-react -f Dockerfile.dev .


# script:
#    - docker run egovelox/docker-react npm run test -- --coverage

script:
    - docker run -e CI=true egovelox/docker-react npm run test